# Generated by Django 4.2.4 on 2023-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('published_date', models.DateTimeField()),
                ('image_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
