# Generated by Django 4.2.4 on 2023-08-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='published_date',
        ),
    ]
