# Generated by Django 4.2.4 on 2023-08-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsitem_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='image_link',
        ),
    ]
